### ISSUE TITLE
请问如何自定义函数

### ISSUE THREAD

**Issue by 759085503** [houlongchao/HLC.Expression#1]
自定义函数如何使用，有没有一个案例

**Comment by houlongchao** [comment]
可以参考这条提交https://github.com/houlongchao/HLC.Expression/commit/43b96d7af570ac624298847d20f5e31a8591a502，其中核心的有2个文件，一个是解析字符串构建表达式树，一个是执行计算。
![image](https://github.com/houlongchao/HLC.Expression/assets/13547836/5aa753b5-7d09-4cdf-9bc1-7b0fbfea9fff)
